# Generated by Django 5.2.3 on 2025-07-01 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Artist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("artist_id", models.CharField(max_length=30)),
                ("name", models.CharField(max_length=200)),
                ("img_url", models.CharField(max_length=400)),
                ("description", models.TextField()),
                ("origin_rul", models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name="Song",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("song_id", models.CharField(max_length=30)),
                ("name", models.CharField(max_length=200)),
                ("lyric", models.TextField()),
                ("cover_img_url", models.CharField(max_length=400)),
                ("origin_url", models.CharField(max_length=400)),
                (
                    "artist",
                    models.ManyToManyField(related_name="songs", to="music.artist"),
                ),
            ],
        ),
    ]
