# Generated by Django 5.2.3 on 2025-07-01 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="artist",
            old_name="origin_rul",
            new_name="origin_url",
        ),
    ]
