# Generated by Django 5.2.3 on 2025-07-03 05:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0003_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="song",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="music.song",
            ),
        ),
    ]
