# Generated by Django 5.2.3 on 2025-07-03 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0004_alter_comment_song"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comment",
            options={"ordering": ["-created_time"]},
        ),
    ]
